# diff Configuration.

log-level = "info"
log-file = "checksum.log"

profile-port = 9999

# for example, the whole data is [1...100]
# we can split these data to [1...10], [11...20], ..., [91...100]
# the [1...10] is a chunk, and it's chunk size is 10
# size of the split chunk
chunk-size = 10000

# how many goroutines are created to check data
check-thread-count = 16

# sampling check percent, for example 10 means only check 10% data
sample-percent = 100

# if check-table is nil, all tables in the schema will be checked.
#[[check-table]]
# table name.
#name = "sbtest2"

# field should be the primary key, unique key or field with index. 
# if comment this, diff will find a suitable field.
#index-field = "id"

# check data's range
#range = "id<100"

[source-db]
host = "127.0.0.1"
port = 4000
user = "root"
password = ""
# schema name
schema = "sbtest4"

