---

# Variables here are applicable to all host groups
backup_dir: "{{ deploy_dir }}/backup"
package_dir: "{{ deploy_dir }}/package"
log_dir: "{{ deploy_dir }}/log"

# Local
ansible_log_dir: "{{ playbook_dir }}/log"
downloads_dir: "{{ playbook_dir }}/downloads"
conf_dir: "{{ playbook_dir }}/conf"
resources_dir: "{{ playbook_dir }}/resources"
script_dir:    "{{ playbook_dir }}/scripts"
binary_dir:    "{{ playbook_dir }}/resources/bin"
fetch_tmp_dir: "{{ playbook_dir }}/fetch_tmp"
fetch_log_dir: "{{ playbook_dir }}/fetch_log"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

deploy_user: "{{ ansible_user }}"